preset: recommended

enabled:
    - yoda_style
    - pre_increment
    - concat_without_spaces

disabled:
    - align_double_arrow
    - trailing_comma_in_multiline_array
    - post_increment
    - concat_with_spaces

finder:
    path:
        - "app/src"
    exclude:
        - "app/tests"
        - "app/src/Migrations"
    not-path:
        - "app/src/Kernel.php"