preset: recommended

enabled:
    - concat_with_spaces
    - yoda_style
    - pre_increment

disabled:
    - align_double_arrow
    - concat_without_spaces
    - trailing_comma_in_multiline_array

finder:
    path:
        - "app/src"
    exclude:
        - "app/tests"
        - "app/src/Migrations"
    not-path:
        - "app/src/Kernel.php"