preset: recommended

enabled:
    - yoda_style
    - pre_increment

disabled:
    - align_double_arrow
    - trailing_comma_in_multiline_array
    - post_increment

finder:
    path:
        - "app/src"
    exclude:
        - "app/tests"
        - "app/src/Migrations"
    not-path:
        - "app/src/Kernel.php"